### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by wesoos** [maxschuster/Vaadin-SignatureField#1]
Hi, this is really great.  You should add it as vaadin addon!

Quick question, how do import this into my project?  Is there a maven dependency?  Which version of vaadin?

Thanks

**Comment by maxschuster** [comment]
Hi @wesoos,

I have uploaded the add-on to the Vaadin Directory and Maven Central.
You can find it here: https://vaadin.com/directory#!addon/signaturefield

It requires Vaadin 7.4+.

The easiest way to import it is using Maven or Ivy, depending on your project type.
Instructions: https://vaadin.com/directory/help/using-vaadin-add-ons

**Comment by wesoos** [comment]
Hi @maxschuster, thanks for uploading it.  I am getting the following error when running my app:

```
Caused by: java.lang.ClassNotFoundException:    eu.maxschuster.vaadin.signaturefield.SignatureField
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450)
at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
... 60 common frames omitted
```

I do see your vaadin-signaturefield-1.0.0.jar in my lib folder, and I am using vaadin 7.5.9...

**Comment by wesoos** [comment]
Max, never mind, it's working, my fault.

**Comment by maxschuster** [comment]
Ok i'll close this issue.
